INCLUDES = -I ./
INCLUDES += -ILPC17XX/Core
INCLUDES += -ILPC17XX/System
INCLUDES += -IDrivers/OLED_1_5
INCLUDES += -IDrivers/BR_SysTick
#INCLUDES += -ILPC17XX/Peripherals/SysTick
#INCLUDES += -ILPC17XX/Peripherals/SPI
#INCLUDES += -ILPC17XX/Peripherals/PCLKPWR
INCLUDES += -ILPC17XX/Peripherals/include

